import {
  Activity,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Ban,
  Bell,
  BookOpen,
  Box,
  Boxes,
  Calendar,
  CalendarDays,
  ChartBar,
  ChartColumn,
  ChartNoAxesCombined,
  ChartPie,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleDot,
  CircleHelp,
  CircleUserRound,
  CircleX,
  ClipboardList,
  Clock,
  Cloud,
  CloudUpload,
  CodeXml,
  Copy,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FilePlus,
  FileText,
  FilePen,
  Filter,
  FolderOpen,
  FolderPlus,
  GitBranch,
  Globe,
  Heart,
  House,
  Image,
  Info,
  KeyRound,
  Layers,
  LayoutDashboard,
  Link,
  LoaderCircle,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Minus,
  Package,
  PanelTop,
  Pause,
  Pencil,
  Phone,
  Play,
  Plus,
  Printer,
  RefreshCw,
  Rocket,
  Save,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Sparkles,
  Star,
  Table2,
  Tag,
  Terminal,
  Trash2,
  TrendingUp,
  Upload,
  UserPlus,
  UserRound,
  Users,
  UsersRound,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-vue-next'

export const iconAliases = {
  dashboard: 'LayoutDashboard',
  project: 'Layers',
  deployment: 'Package',
  setting: 'Settings',
  components: 'PanelTop',
  chart: 'ChartNoAxesCombined',
  icons: 'CircleHelp',
  table: 'Table2',
  form: 'FileText',
  feedback: 'Bell',
  result: 'CheckCircle2',
  tokens: 'Layers',
  external: 'ExternalLink',
} as const

export type FluffyIconAlias = keyof typeof iconAliases

const iconRegistry: Record<string, LucideIcon> = {
  Activity,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Ban,
  Bell,
  BookOpen,
  Box,
  Boxes,
  Calendar,
  CalendarDays,
  ChartBar,
  ChartColumn,
  ChartNoAxesCombined,
  ChartPie,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleDot,
  CircleHelp,
  CircleUserRound,
  CircleX,
  ClipboardList,
  Clock,
  Cloud,
  CloudUpload,
  CodeXml,
  Copy,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FilePlus,
  FileText,
  FilePen,
  Filter,
  FolderOpen,
  FolderPlus,
  GitBranch,
  Globe,
  Heart,
  House,
  Image,
  Info,
  KeyRound,
  Layers,
  LayoutDashboard,
  Link,
  LoaderCircle,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Minus,
  Package,
  PanelTop,
  Pause,
  Pencil,
  Phone,
  Play,
  Plus,
  Printer,
  RefreshCw,
  Rocket,
  Save,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Sparkles,
  Star,
  Table2,
  Tag,
  Terminal,
  Trash2,
  TrendingUp,
  Upload,
  UserPlus,
  UserRound,
  Users,
  UsersRound,
  X,
  Zap,
}

export const builtinIconNames: readonly string[] = Object.keys(iconRegistry)

function toPascalCase(name: string) {
  return name.replace(/(^|[-_\s])([a-z\d])/g, (_, __, character: string) => character.toUpperCase())
}

export function registerIcons(icons: Record<string, LucideIcon>) {
  for (const [name, component] of Object.entries(icons)) {
    iconRegistry[toPascalCase(name)] = component
  }
}

export function resolveIcon(name: string): LucideIcon | undefined {
  const resolvedName = name in iconAliases ? iconAliases[name as FluffyIconAlias] : toPascalCase(name)
  return iconRegistry[resolvedName]
}
