import { createI18n } from 'vue-i18n'
import { appConfig } from '@/config/app'

const messages = {
  'zh-CN': {
    navigation: { workspace: '工作区', showcase: '展示', manage: '管理', resources: '资源', home: '概览', projects: '项目', deployments: '部署', settings: '设置', components: '组件展示', charts: 'ECharts 图表', icons: '图标', tree: '树形结构', table: '数据表格', forms: '表单', feedback: '反馈状态', results: '结果页', tokens: '设计令牌', login: '登录', vueDocs: 'Vue 文档', exampleFrame: '嵌入示例', external: '外部页面' },
    shell: { controls: '全局控制', search: '搜索', searchPlaceholder: '搜索页面和快捷操作…', noResults: '没有匹配的页面', commandHint: '使用上下方向键选择，按 Enter 跳转', notifications: '通知', account: '账户', settings: '设置', accountSettings: '账户设置', logout: '退出登录', collapse: '切换导航', theme: '切换主题', language: '切换语言', enterFullscreen: '进入全屏', exitFullscreen: '退出全屏', markAllRead: '全部已读', closeNavigation: '关闭导航', navigation: '主导航', tabs: '页面标签', closeTab: '关闭标签页', closeCurrent: '关闭当前标签页', closeLeft: '关闭左侧标签页', closeRight: '关闭右侧标签页', closeOthers: '关闭其他标签页', closeAll: '关闭全部标签页', reload: '重新加载', team: '团队', allSystemsOperational: '所有系统正常', footerStatus: '由 Fluffy Design Pro 驱动', uploadCenter: '上传中心' },
    panel: { title: '偏好设置', layout: '布局', appearance: '外观', tabBar: '标签栏', navbar: '导航栏', menu: '菜单栏', menuWidth: '菜单宽度', colorWeak: '色弱模式', colorWeakHint: '以灰度显示界面', documentTitle: '页面标题', documentTitleHint: '在浏览器标签页显示当前页面标题', width220: '窄 (220px)', width244: '默认 (244px)', width280: '宽 (280px)' },
    notification: { title: '消息通知', empty: '暂无通知', viewAll: '查看全部', time: '刚刚' },
    common: { healthy: '运行正常', review: '待审核', ready: '已就绪', building: '构建中', failed: '失败', close: '关闭', back: '返回', retry: '重试', loading: '加载中' },
    feedback: { toast: '通知', success: '成功', info: '提示', warning: '警告', error: '错误', loading: '加载状态', skeleton: '骨架屏', toggle: '切换', loaded: '内容已就绪，周围布局保持不变。' },
    home: { eyebrow: '工作区概览', title: '早上好，Fluffy', description: '这里汇总了项目、部署和团队活动的最新状态。', action: '打开项目', metrics: '关键指标', projects: '活跃项目', deployments: '本周部署', teamMembers: '团队成员', sinceLastWeek: '较上周', recentActivity: '最近活动', activityDescription: '工作区中的最新变更', viewAll: '查看全部', deploymentCompleted: '生产环境部署已完成', projectCreated: '创建了新的项目', memberJoined: '新的团队成员已加入', production: '生产环境', platformStatus: '平台状态', statusDescription: '核心服务运行正常', healthy: '运行正常', edgeNetwork: '边缘网络', buildPipeline: '构建流水线', activityStream: '活动流', operational: '正常', quickActions: '快速开始', quickActionsDescription: '常用工作区操作', newProject: '创建项目', newProjectDescription: '从模板开始新的服务', inviteMember: '邀请成员', inviteMemberDescription: '将协作者添加到团队', reviewDeployments: '查看部署', reviewDeploymentsDescription: '检查最近的生产发布' },
    projects: { eyebrow: '项目空间', title: '项目', description: '在一个位置查看团队所有服务的运行状态。', newProject: '创建项目', active: '活跃项目', activeDescription: '具有最近活动和部署记录的服务。', items: '个项目' },
    deployments: { eyebrow: '发布记录', title: '部署', description: '追踪生产和预览环境中的最近发布。', deploy: '创建部署', deployment: '部署', environment: '环境', status: '状态', duration: '耗时', updated: '更新时间' },
    settings: { eyebrow: '工作区配置', title: '设置', description: '管理团队偏好和通知方式。', workspaceName: '工作区名称', notifications: '部署通知', notificationsDescription: '在生产部署完成后通知团队。', save: '保存更改', saved: '更改已保存' },
    showcase: { eyebrow: '设计系统展示', componentsTitle: '组件', componentsDescription: '用于控制台界面的基础交互状态和表面层级。', chartsTitle: 'ECharts 图表', chartsDescription: '按需注册的响应式图表示例。', traffic: '平台流量', trafficDescription: '请求量与部署频次趋势。', lastSevenDays: '最近 7 天', iconsTitle: '图标', iconsDescription: 'FIcon 内置常用 Lucide 图标集，支持名称、路由别名、颜色和尺寸；额外图标由应用显式注册。', registeredIconsTitle: '应用注册图标', registeredIconsDescription: '内置集之外的图标由应用在入口通过 registerIcons 显式注册后即可使用。', tableTitle: '数据表格', tableDescription: '展示本地与请求式数据管理、分页和加载状态。', filter: '筛选项目…', noResults: '没有匹配的记录', formsTitle: '表单', formsDescription: '同一套字段可手动组合，也可由 columns 自动渲染。', manualForm: '手动表单', autoForm: '自动表单', feedbackTitle: '反馈状态', feedbackDescription: 'Toast、skeleton、spinner 和空状态用于缩短等待感。', resultsTitle: '结果页', resultsDescription: '标准化完成、提醒和失败后的下一步。', tokensTitle: '设计令牌', tokensDescription: '应用壳使用的语义色、圆角和阴影变量。' },
    components: { buttons: '按钮', code: '代码块', markdown: 'Markdown 预览', inputs: '输入控件', formField: '表单字段', loading: '加载状态', results: '结果状态', toast: '通知反馈', primary: '主操作', secondary: '次操作', ghost: '幽灵按钮', danger: '危险操作', loadingDemo: '加载中', disabled: '禁用', text: '文本输入', email: '邮箱地址', password: '密码', select: '下拉选择', textarea: '多行文本', checkbox: '复选框', optionA: '选项 A', optionB: '选项 B', optionC: '选项 C', textPlaceholder: '请输入内容', textareaPlaceholder: '输入一段描述…', requiredLabel: '必填字段', helpLabel: '带帮助文本的字段', errorLabel: '带错误状态的字段', requiredHint: '标记为必填', helpHint: '这是一段帮助说明', errorHint: '该字段校验未通过', spinnerSm: '小尺寸', spinnerMd: '标准尺寸', resultSuccess: '部署成功', resultSuccessDesc: '生产环境已发布最新构建。', resultInfo: '新的通知', resultInfoDesc: '有一条来自团队的新消息。', resultWarning: '发布前确认', resultWarningDesc: '请检查发布设置后再继续。', resultError: '请求失败', resultErrorDesc: '服务暂时不可用，请稍后重试。', toastSuccess: '成功', toastInfo: '提示', toastWarning: '警告', toastError: '错误', empty: '空状态', emptyTitle: '暂无项目', emptyDesc: '创建第一个项目后，它会出现在这里。', emptyAction: '创建项目', emptyFilteredTitle: '没有匹配的结果', emptyFilteredDesc: '调整筛选条件后再试一次。', upload: '文件上传', uploadProgress: '上传进度' },
    table: { name: '名称', owner: '负责人', status: '状态', updated: '更新时间', page: '第 {page} 页', total: '共 {total} 条', previous: '上一页', next: '下一页', refresh: '刷新数据', remote: '请求数据', loadError: '数据加载失败，请稍后重试' },
    form: { submit: '提交', reset: '重置', required: '这是必填项', pattern: '输入格式不正确', name: '名称', email: '邮箱地址', role: '角色', bio: '简介', subscribe: '接收更新', namePlaceholder: '输入显示名称', emailPlaceholder: "name{'@'}example.com", bioPlaceholder: '介绍一下你的工作内容', saved: '表单已提交' },
    code: { copy: '复制', copied: '已复制', collapse: '折叠代码', expand: '展开代码' },
    toast: { dismiss: '关闭通知', success: '操作已完成', info: '已更新展示内容', warning: '请先检查表单内容', error: '请求未能完成' },
    login: { eyebrow: 'Fluffy 控制台', slogan: '让每一次交付都更清晰。', description: '在一个平静、专注的工作区中管理项目、发布和团队活动。', welcome: '欢迎回来', detail: '输入演示账号继续访问控制台。', email: '邮箱地址', password: '密码', passwordPlaceholder: '输入任意密码', submit: '进入控制台', success: '登录演示已完成' },
    result: { successTitle: '部署已准备就绪', successDescription: '生产环境已经接收到最新构建。', warningTitle: '还需要一次确认', warningDescription: '请检查发布设置后再继续。', errorTitle: '未能完成请求', errorDescription: '没有数据被修改，你可以调整后重试。', infoTitle: '暂时没有结果', infoDescription: '创建第一条记录后，它会出现在这里。', viewProjects: '查看项目' },
    tokens: { colors: '语义颜色', surfaces: '表面层级', radius: '圆角', shadows: '阴影', focus: '焦点环' },
    external: { eyebrow: '外部资源', description: '该页面在受限 iframe 容器中渲染；若被站点策略阻止，请在新窗口打开。', openNewTab: '在新窗口打开', unavailable: '该外部资源不可用' },
    notFound: { eyebrow: '404', title: '此页面不存在', description: '链接可能已过期，或资源已经被移动。', path: '未找到的路径', action: '返回概览', back: '返回上一页' },
    upload: { center: { title: '上传中心', clearCompleted: '清除已完成', empty: '暂无上传任务', manage: '管理上传' }, tab: { uploading: '上传中', done: '已完成', failed: '失败' }, status: { uploading: '上传中', done: '已完成', error: '失败' }, dropzone: '点击或拖拽文件到此处上传', simulated: 'OSS 未配置，当前为模拟上传', retry: '重试', remove: '移除', error: { failed: '上传失败，请重试' } }
  },
  'en-US': {
    navigation: { workspace: 'Workspace', showcase: 'Showcase', manage: 'Manage', resources: 'Resources', home: 'Overview', projects: 'Projects', deployments: 'Deployments', settings: 'Settings', components: 'Components', charts: 'ECharts', icons: 'Icons', tree: 'Tree', table: 'Data table', forms: 'Forms', feedback: 'Feedback', results: 'Results', tokens: 'Design tokens', login: 'Login', vueDocs: 'Vue documentation', exampleFrame: 'Embedded example', external: 'External page' },
    shell: { controls: 'Global controls', search: 'Search', searchPlaceholder: 'Search pages and quick actions…', noResults: 'No matching pages', commandHint: 'Use arrow keys to select and Enter to navigate', notifications: 'Notifications', account: 'Account', settings: 'Settings', accountSettings: 'Account settings', logout: 'Log out', collapse: 'Toggle navigation', theme: 'Toggle theme', language: 'Switch language', enterFullscreen: 'Enter fullscreen', exitFullscreen: 'Exit fullscreen', markAllRead: 'Mark all as read', closeNavigation: 'Close navigation', navigation: 'Main navigation', tabs: 'Page tabs', closeTab: 'Close tab', closeCurrent: 'Close current tab', closeLeft: 'Close tabs to the left', closeRight: 'Close tabs to the right', closeOthers: 'Close other tabs', closeAll: 'Close all tabs', reload: 'Reload', team: 'Team', allSystemsOperational: 'All systems operational', footerStatus: 'Powered by Fluffy Design Pro', uploadCenter: 'Upload center' },
    panel: { title: 'Preferences', layout: 'Layout', appearance: 'Appearance', tabBar: 'Tab bar', navbar: 'Navbar', menu: 'Menu', menuWidth: 'Menu width', colorWeak: 'Color-weak mode', colorWeakHint: 'Render the interface in grayscale', documentTitle: 'Page title', documentTitleHint: 'Show the current page title in the browser tab', width220: 'Narrow (220px)', width244: 'Default (244px)', width280: 'Wide (280px)' },
    notification: { title: 'Notifications', empty: 'No notifications', viewAll: 'View all', time: 'just now' },
    common: { healthy: 'Healthy', review: 'In review', ready: 'Ready', building: 'Building', failed: 'Failed', close: 'Close', back: 'Back', retry: 'Retry', loading: 'Loading' },
    feedback: { toast: 'Toast', success: 'Success', info: 'Info', warning: 'Warning', error: 'Error', loading: 'Loading', skeleton: 'Skeleton', toggle: 'Toggle', loaded: 'The content is ready without changing the surrounding layout.' },
    home: { eyebrow: 'Workspace overview', title: 'Good morning, Fluffy', description: 'A concise view of your projects, deployments, and team activity.', action: 'Open projects', metrics: 'Key metrics', projects: 'Active projects', deployments: 'Deployments this week', teamMembers: 'Team members', sinceLastWeek: 'from last week', recentActivity: 'Recent activity', activityDescription: 'The latest changes across your workspace', viewAll: 'View all', deploymentCompleted: 'Production deployment completed', projectCreated: 'Created a new project', memberJoined: 'A new teammate joined', production: 'Production', platformStatus: 'Platform status', statusDescription: 'Core services are running normally', healthy: 'Healthy', edgeNetwork: 'Edge network', buildPipeline: 'Build pipeline', activityStream: 'Activity stream', operational: 'Operational', quickActions: 'Quick actions', quickActionsDescription: 'Common workspace tasks', newProject: 'Create a project', newProjectDescription: 'Start a new service from a template', inviteMember: 'Invite a member', inviteMemberDescription: 'Add a collaborator to your team', reviewDeployments: 'Review deployments', reviewDeploymentsDescription: 'Inspect recent production releases' },
    projects: { eyebrow: 'Project space', title: 'Projects', description: 'See the health of every service your team operates.', newProject: 'New project', active: 'Active projects', activeDescription: 'Services with recent activity and deployments.', items: 'projects' },
    deployments: { eyebrow: 'Release history', title: 'Deployments', description: 'Track recent releases across production and preview environments.', deploy: 'Create deployment', deployment: 'Deployment', environment: 'Environment', status: 'Status', duration: 'Duration', updated: 'Updated' },
    settings: { eyebrow: 'Workspace configuration', title: 'Settings', description: 'Manage team preferences and notification delivery.', workspaceName: 'Workspace name', notifications: 'Deployment notifications', notificationsDescription: 'Notify the team when production deployments complete.', save: 'Save changes', saved: 'Changes saved' },
    showcase: { eyebrow: 'Design system showcase', componentsTitle: 'Components', componentsDescription: 'Core interaction states and surface hierarchy for console interfaces.', chartsTitle: 'ECharts', chartsDescription: 'A responsive chart example with on-demand registration.', traffic: 'Platform traffic', trafficDescription: 'Request and deployment trends.', lastSevenDays: 'Last 7 days', iconsTitle: 'Icons', iconsDescription: 'FIcon ships a common Lucide icon set with name, route-alias, color, and size support; extra icons are registered by the app.', registeredIconsTitle: 'App-registered icons', registeredIconsDescription: 'Icons outside the built-in set are registered explicitly by the app via registerIcons before use.', tableTitle: 'Data table', tableDescription: 'Local and requested data, pagination, and loading states.', filter: 'Filter projects…', noResults: 'No matching records', formsTitle: 'Forms', formsDescription: 'Compose fields manually or render them from columns.', manualForm: 'Manual form', autoForm: 'Auto form', feedbackTitle: 'Feedback', feedbackDescription: 'Toast, skeleton, spinner, and empty states reduce perceived wait time.', resultsTitle: 'Results', resultsDescription: 'Standard next steps after success, warning, or failure.', tokensTitle: 'Design tokens', tokensDescription: 'Semantic colors, radii, and shadows used by the app shell.' },
    components: { buttons: 'Buttons', code: 'Code block', markdown: 'Markdown preview', inputs: 'Inputs', formField: 'Form field', loading: 'Loading', results: 'Results', toast: 'Toast', primary: 'Primary', secondary: 'Secondary', ghost: 'Ghost', danger: 'Danger', loadingDemo: 'Loading', disabled: 'Disabled', text: 'Text input', email: 'Email', password: 'Password', select: 'Select', textarea: 'Textarea', checkbox: 'Checkbox', optionA: 'Option A', optionB: 'Option B', optionC: 'Option C', textPlaceholder: 'Type something…', textareaPlaceholder: 'Write a description…', requiredLabel: 'Required field', helpLabel: 'Field with help', errorLabel: 'Field with error', requiredHint: 'Marked as required', helpHint: 'A short help message.', errorHint: 'This field is invalid', spinnerSm: 'Small', spinnerMd: 'Default', resultSuccess: 'Deployment ready', resultSuccessDesc: 'Production has received the latest build.', resultInfo: 'New notification', resultInfoDesc: 'There is a new message from your team.', resultWarning: 'Confirm release', resultWarningDesc: 'Review release settings before continuing.', resultError: 'Request failed', resultErrorDesc: 'The service is temporarily unavailable. Try again later.', toastSuccess: 'Success', toastInfo: 'Info', toastWarning: 'Warning', toastError: 'Error', empty: 'Empty state', emptyTitle: 'No projects yet', emptyDesc: 'Your first project will appear here.', emptyAction: 'Create project', emptyFilteredTitle: 'No matching results', emptyFilteredDesc: 'Adjust the filters and try again.', upload: 'File upload', uploadProgress: 'Upload progress' },
    table: { name: 'Name', owner: 'Owner', status: 'Status', updated: 'Updated', page: 'Page {page}', total: '{total} total', previous: 'Previous', next: 'Next', refresh: 'Refresh data', remote: 'Request data', loadError: 'Failed to load data, please try again' },
    form: { submit: 'Submit', reset: 'Reset', required: 'This field is required', pattern: 'The value has an invalid format', name: 'Name', email: 'Email address', role: 'Role', bio: 'Bio', subscribe: 'Receive updates', namePlaceholder: 'Enter a display name', emailPlaceholder: "name{'@'}example.com", bioPlaceholder: 'Tell us about your work', saved: 'Form submitted' },
    code: { copy: 'Copy', copied: 'Copied', collapse: 'Collapse code', expand: 'Expand code' },
    toast: { dismiss: 'Dismiss notification', success: 'Action completed', info: 'Demo content updated', warning: 'Review the form first', error: 'The request could not complete' },
    login: { eyebrow: 'Fluffy Console', slogan: 'Make every delivery clearer.', description: 'Manage projects, releases, and team activity in one calm workspace.', welcome: 'Welcome back', detail: 'Enter a demo account to access the console.', email: 'Email address', password: 'Password', passwordPlaceholder: 'Enter any password', submit: 'Enter console', success: 'Login demo completed' },
    result: { successTitle: 'Deployment is ready', successDescription: 'Production has received the latest build.', warningTitle: 'One confirmation remains', warningDescription: 'Review release settings before continuing.', errorTitle: 'The request could not complete', errorDescription: 'No data changed. Adjust it and try again.', infoTitle: 'No results yet', infoDescription: 'Your first record will appear here.', viewProjects: 'View projects' },
    tokens: { colors: 'Semantic colors', surfaces: 'Surface layers', radius: 'Radii', shadows: 'Shadows', focus: 'Focus ring' },
    external: { eyebrow: 'External resource', description: 'This page renders in a restricted iframe. Open it in a new tab if the site blocks embedding.', openNewTab: 'Open in new tab', unavailable: 'This external resource is unavailable' },
    notFound: { eyebrow: '404', title: 'This page does not exist', description: 'The link may be outdated or the resource has moved.', path: 'Missing path', action: 'Back to overview', back: 'Go back' },
    upload: { center: { title: 'Upload center', clearCompleted: 'Clear completed', empty: 'No upload tasks', manage: 'Manage uploads' }, tab: { uploading: 'Uploading', done: 'Completed', failed: 'Failed' }, status: { uploading: 'Uploading', done: 'Completed', error: 'Failed' }, dropzone: 'Click or drag files here to upload', simulated: 'OSS is not configured, upload is simulated', retry: 'Retry', remove: 'Remove', error: { failed: 'Upload failed, please retry' } }
  }
}

export const i18n = createI18n({ legacy: false, locale: appConfig.defaultLocale, fallbackLocale: 'en-US', messages })
