import { createI18n } from 'vue-i18n'
import { appConfig } from '@/config/app'

const messages = {
  'zh-CN': {
    navigation: { workspace: '工作区', workspaceHome: '文档工作区', packages: '源文件解析', showcase: '展示', manage: '管理', resources: '资源浏览', modding: '模组/资产制作', export: '预览与导出', home: '概览', projects: '项目', deployments: '部署', settings: '设置', components: '组件展示', charts: 'ECharts 图表', icons: '图标', tree: '树形结构', table: '数据表格', forms: '表单', feedback: '反馈状态', results: '结果页', tokens: '设计令牌', login: '登录', vueDocs: 'Vue 文档', exampleFrame: '嵌入示例', external: '外部页面' },
    shell: { controls: '全局控制', search: '搜索', searchPlaceholder: '搜索页面和快捷操作…', noResults: '没有匹配的页面', commandHint: '使用上下方向键选择，按 Enter 跳转', notifications: '通知', account: '账户', settings: '设置', accountSettings: '账户设置', logout: '退出登录', collapse: '切换导航', theme: '切换主题', language: '切换语言', enterFullscreen: '进入全屏', exitFullscreen: '退出全屏', markAllRead: '全部已读', closeNavigation: '关闭导航', navigation: '主导航', tabs: '页面标签', closeTab: '关闭标签页', closeCurrent: '关闭当前标签页', closeLeft: '关闭左侧标签页', closeRight: '关闭右侧标签页', closeOthers: '关闭其他标签页', closeAll: '关闭全部标签页', reload: '重新加载', team: '团队', allSystemsOperational: '所有系统正常', footerStatus: '由 Fluffy Design Pro 驱动', uploadCenter: '上传中心' },
    panel: { title: '偏好设置', layout: '布局', appearance: '外观', tabBar: '标签栏', navbar: '导航栏', menu: '菜单栏', menuWidth: '菜单宽度', colorWeak: '色弱模式', colorWeakHint: '以灰度显示界面', documentTitle: '页面标题', documentTitleHint: '在浏览器标签页显示当前页面标题', width220: '窄 (220px)', width244: '默认 (244px)', width280: '宽 (280px)' },
    notification: { title: '消息通知', empty: '暂无通知', viewAll: '查看全部', time: '刚刚' },
    common: { healthy: '运行正常', review: '待审核', ready: '已就绪', building: '构建中', failed: '失败', close: '关闭', back: '返回', retry: '重试', loading: '加载中', refresh: '刷新' },
    feedback: { toast: '通知', success: '成功', info: '提示', warning: '警告', error: '错误', loading: '加载状态', skeleton: '骨架屏', toggle: '切换', loaded: '内容已就绪，周围布局保持不变。' },
    home: { eyebrow: 'OpenSCP 工作台', title: '资源地图', description: '从 package 索引、资产组件到开发者文档，保持每一层都可追溯。', openDocs: '打开文档', openPackage: '打开 package', mockNotice: '当前使用浏览器 Mock 数据；连接 Tauri 后将读取真实 package。', packages: 'Packages', resources: '资源', assets: '资产', failedOperations: '失败任务', recentPackages: '最近打开', recentPackagesDescription: '继续处理最近查看的 package。', opens: '次打开', noPackages: '还没有打开过 package。', activity: '最近活动', noActivity: '暂无活动记录', metrics: '工作台概览', projects: '活跃项目', deployments: '本周部署', teamMembers: '团队成员', sinceLastWeek: '较上周', recentActivity: '最近活动', activityDescription: '工作区中的最新变更', viewAll: '查看全部', deploymentCompleted: '生产环境部署已完成', projectCreated: '创建了新的项目', memberJoined: '新的团队成员已加入', production: '生产环境', platformStatus: '平台状态', statusDescription: '核心服务运行正常', healthy: '运行正常', edgeNetwork: '边缘网络', buildPipeline: '构建流水线', activityStream: '活动流', operational: '正常', quickActions: '快速开始', quickActionsDescription: '常用工作区操作', newProject: '创建项目', newProjectDescription: '从模板开始新的服务', inviteMember: '邀请成员', inviteMemberDescription: '将协作者添加到团队', reviewDeployments: '查看部署', reviewDeploymentsDescription: '检查最近的生产发布' },
    projects: { eyebrow: '项目空间', title: '项目', description: '在一个位置查看团队所有服务的运行状态。', newProject: '创建项目', active: '活跃项目', activeDescription: '具有最近活动和部署记录的服务。', items: '个项目' },
    deployments: { eyebrow: '发布记录', title: '部署', description: '追踪生产和预览环境中的最近发布。', deploy: '创建部署', deployment: '部署', environment: '环境', status: '状态', duration: '耗时', updated: '更新时间' },
    settings: { eyebrow: '工作区配置', title: '设置', description: '管理团队偏好和通知方式。', workspaceName: '工作区名称', notifications: '部署通知', notificationsDescription: '在生产部署完成后通知团队。', save: '保存更改', saved: '更改已保存', gameDirectoryTitle: '游戏数据目录', gameDirectoryDescription: '用于探测 SimCity 数据包和资源的本地目录。', gameDirectoryLabel: '目录路径', gameDirectoryPlaceholder: '例如：D:/ea-games/SimCity', gameDirectoryUnavailable: '当前目录不可用，请重新选择。', detectedCandidates: '探测到的目录', packageMarkerFound: '发现 package 文件', noPackageMarker: '未发现直接 package 文件', workspaceTitle: '文档工作区', workspaceDescription: '按模组、资产和组件组织 Markdown 文档。', workspaceNotConfigured: '尚未选择文档工作区', openWorkspace: '打开工作区' },
    workspace: { eyebrow: '开发者文档', title: '文档工作区', description: '用文件夹整理模组、资产与组件，让每个决定都有出处。', chooseTitle: '选择一个文档工作区', chooseDescription: '工作区只保存 Markdown 文件；OpenSCP 会记录文件夹与 README 的相对关系。', rootLabel: '工作区路径', rootPlaceholder: '输入本地文件夹路径', openRoot: '设置工作区', newFolder: '新建文件夹', folderPlaceholder: 'mods/example', createFolder: '创建并写入 README', folders: '文件夹', empty: '工作区还没有文件夹。创建第一个模组或资产目录。', revision: '版本', preview: '预览', edit: '编辑', save: '保存 Markdown', markdownLabel: 'Markdown 内容', selectTitle: '选择一个文件夹', selectDescription: '从左侧选择文件夹，打开它的 README.md。' },
    runtime: { browserNotice: '当前运行在浏览器预览模式；Tauri 文件能力将在桌面应用中可用。' },
    package: { eyebrow: '资源浏览', title: '源文件解析', ideDescription: '像 IDE 一样浏览游戏目录、package 和资源。', fileTree: '文件树', packageFiles: 'Package 文件', noFolders: '还没有选择文件夹', noPackagesInFolder: '此文件夹没有 package', chooseFolderHint: '从顶部导入菜单选择一个文件夹。', importMode: '导入方式', chooseFolder: '选择文件夹', useDefaultFolder: '使用默认目录', import: '导入', mockSource: '浏览器 Mock 数据', liveSource: 'Tauri 实时数据', openPackages: '已打开的 package', resourceCategories: '资源分类', all: '全部', rw4: 'RW4', raster: 'Raster', property: 'Property', text: 'Text', media: 'Media', tgi: 'TGI', storage: '存储', compression: '压缩', compressed: '已压缩', stored: '未压缩', noCategoryResources: '此分类暂无资源', adjustCategory: '切换其他分类继续浏览。', emptyWorkspaceTitle: '工作区已准备好', emptyWorkspaceDescription: '从左侧选择文件夹，然后打开一个 package。', selectPackageTitle: '选择一个 package', selectPackageDescription: 'package 会在这里以独立 Tab 打开。', emptyDetailTitle: '选择一个资源', emptyDetailDescription: '资源详情将在右侧工作区显示。', bytesReady: '选择 Hex、文本或其他预览方式。', hex: 'Hex', preview: '预览', runtimeNotice: '当前为浏览器预览；请在 Tauri 桌面应用中打开游戏包。', pathLabel: 'package 路径', pathPlaceholder: 'D:/ea-games/SimCity/SimCityData/…', open: '打开 package', resources: '项资源', resourceList: '资源列表', pageSummary: '第 {page} 页 · 共 {total} 项', filterPlaceholder: '按 TGI 筛选', emptyTitle: '没有资源', emptyDescription: '这个 package 没有可显示的索引资源。', resourceDetail: '资源详情', offset: '文件偏移', storedSize: '存储大小', decompressedSize: '解压大小', hexPreview: '前 4KB 内容', noBytes: '没有读取到字节', selectResource: '选择资源查看详情' },
    showcase: { eyebrow: '设计系统展示', componentsTitle: '组件', componentsDescription: '用于控制台界面的基础交互状态和表面层级。', chartsTitle: 'ECharts 图表', chartsDescription: '按需注册的响应式图表示例。', traffic: '平台流量', trafficDescription: '请求量与部署频次趋势。', lastSevenDays: '最近 7 天', iconsTitle: '图标', iconsDescription: 'FIcon 内置常用 Lucide 图标集，支持名称、路由别名、颜色和尺寸；额外图标由应用显式注册。', registeredIconsTitle: '应用注册图标', registeredIconsDescription: '内置集之外的图标由应用在入口通过 registerIcons 显式注册后即可使用。', tableTitle: '数据表格', tableDescription: '展示本地与请求式数据管理、分页和加载状态。', filter: '筛选项目…', noResults: '没有匹配的记录', formsTitle: '表单', formsDescription: '同一套字段可手动组合，也可由 columns 自动渲染。', manualForm: '手动表单', autoForm: '自动表单', feedbackTitle: '反馈状态', feedbackDescription: 'Toast、skeleton、spinner 和空状态用于缩短等待感。', resultsTitle: '结果页', resultsDescription: '标准化完成、提醒和失败后的下一步。', tokensTitle: '设计令牌', tokensDescription: '应用壳使用的语义色、圆角和阴影变量。' },
    components: { buttons: '按钮', code: '代码块', markdown: 'Markdown 预览', inputs: '输入控件', formField: '表单字段', loading: '加载状态', results: '结果状态', toast: '通知反馈', primary: '主操作', secondary: '次操作', ghost: '幽灵按钮', danger: '危险操作', loadingDemo: '加载中', disabled: '禁用', text: '文本输入', email: '邮箱地址', password: '密码', select: '下拉选择', textarea: '多行文本', checkbox: '复选框', optionA: '选项 A', optionB: '选项 B', optionC: '选项 C', textPlaceholder: '请输入内容', textareaPlaceholder: '输入一段描述…', requiredLabel: '必填字段', helpLabel: '带帮助文本的字段', errorLabel: '带错误状态的字段', requiredHint: '标记为必填', helpHint: '这是一段帮助说明', errorHint: '该字段校验未通过', spinnerSm: '小尺寸', spinnerMd: '标准尺寸', resultSuccess: '部署成功', resultSuccessDesc: '生产环境已发布最新构建。', resultInfo: '新的通知', resultInfoDesc: '有一条来自团队的新消息。', resultWarning: '发布前确认', resultWarningDesc: '请检查发布设置后再继续。', resultError: '请求失败', resultErrorDesc: '服务暂时不可用，请稍后重试。', toastSuccess: '成功', toastInfo: '提示', toastWarning: '警告', toastError: '错误', empty: '空状态', emptyTitle: '暂无项目', emptyDesc: '创建第一个项目后，它会出现在这里。', emptyAction: '创建项目', emptyFilteredTitle: '没有匹配的结果', emptyFilteredDesc: '调整筛选条件后再试一次。', upload: '文件上传', uploadProgress: '上传进度' },
    table: { name: '名称', owner: '负责人', status: '状态', updated: '更新时间', page: '第 {page} 页', total: '共 {total} 条', previous: '上一页', next: '下一页', refresh: '刷新数据', remote: '请求数据', loadError: '数据加载失败，请稍后重试' },
    form: { submit: '提交', reset: '重置', required: '这是必填项', pattern: '输入格式不正确', name: '名称', email: '邮箱地址', role: '角色', bio: '简介', subscribe: '接收更新', namePlaceholder: '输入显示名称', emailPlaceholder: "name{'@'}example.com", bioPlaceholder: '介绍一下你的工作内容', saved: '表单已提交' },
    code: { copy: '复制', copied: '已复制', collapse: '折叠代码', expand: '展开代码' },
    toast: { dismiss: '关闭通知', success: '操作已完成', info: '已更新展示内容', warning: '请先检查表单内容', error: '请求未能完成' },
    login: { eyebrow: 'Fluffy 控制台', slogan: '让每一次交付都更清晰。', description: '在一个平静、专注的工作区中管理项目、发布和团队活动。', welcome: '欢迎回来', detail: '输入演示账号继续访问控制台。', email: '邮箱地址', password: '密码', passwordPlaceholder: '输入任意密码', submit: '进入控制台', success: '登录演示已完成' },
    result: { successTitle: '部署已准备就绪', successDescription: '生产环境已经接收到最新构建。', warningTitle: '还需要一次确认', warningDescription: '请检查发布设置后再继续。', errorTitle: '未能完成请求', errorDescription: '没有数据被修改，你可以调整后重试。', infoTitle: '暂时没有结果', infoDescription: '创建第一条记录后，它会出现在这里。', viewProjects: '查看项目' },
    tokens: { colors: '语义颜色', surfaces: '表面层级', radius: '圆角', shadows: '阴影', focus: '焦点环' },
    external: { eyebrow: '外部资源', description: '该页面在受限 iframe 容器中渲染；若被站点策略阻止，请在新窗口打开。', openNewTab: '在新窗口打开', unavailable: '该外部资源不可用' },
    notFound: { eyebrow: '404', title: '此页面不存在', description: '链接可能已过期，或资源已经被移动。', path: '未找到的路径', action: '返回概览', back: '返回上一页' },
    upload: { center: { title: '上传中心', clearCompleted: '清除已完成', empty: '暂无上传任务', manage: '管理上传' }, tab: { uploading: '上传中', done: '已完成', failed: '失败' }, status: { uploading: '上传中', done: '已完成', error: '失败' }, dropzone: '点击或拖拽文件到此处上传', simulated: 'OSS 未配置，当前为模拟上传', retry: '重试', remove: '移除', error: { failed: '上传失败，请重试' } }
  },
  'en-US': {
    navigation: { workspace: 'Workspace', workspaceHome: 'Docs workspace', packages: 'Source parsing', showcase: 'Showcase', manage: 'Manage', resources: 'Resource browser', modding: 'Modding / asset creation', export: 'Preview & export', home: 'Overview', projects: 'Projects', deployments: 'Deployments', settings: 'Settings', components: 'Components', charts: 'ECharts', icons: 'Icons', tree: 'Tree', table: 'Data table', forms: 'Forms', feedback: 'Feedback', results: 'Results', tokens: 'Design tokens', login: 'Login', vueDocs: 'Vue documentation', exampleFrame: 'Embedded example', external: 'External page' },
    shell: { controls: 'Global controls', search: 'Search', searchPlaceholder: 'Search pages and quick actions…', noResults: 'No matching pages', commandHint: 'Use arrow keys to select and Enter to navigate', notifications: 'Notifications', account: 'Account', settings: 'Settings', accountSettings: 'Account settings', logout: 'Log out', collapse: 'Toggle navigation', theme: 'Toggle theme', language: 'Switch language', enterFullscreen: 'Enter fullscreen', exitFullscreen: 'Exit fullscreen', markAllRead: 'Mark all as read', closeNavigation: 'Close navigation', navigation: 'Main navigation', tabs: 'Page tabs', closeTab: 'Close tab', closeCurrent: 'Close current tab', closeLeft: 'Close tabs to the left', closeRight: 'Close tabs to the right', closeOthers: 'Close other tabs', closeAll: 'Close all tabs', reload: 'Reload', team: 'Team', allSystemsOperational: 'All systems operational', footerStatus: 'Powered by Fluffy Design Pro', uploadCenter: 'Upload center' },
    panel: { title: 'Preferences', layout: 'Layout', appearance: 'Appearance', tabBar: 'Tab bar', navbar: 'Navbar', menu: 'Menu', menuWidth: 'Menu width', colorWeak: 'Color-weak mode', colorWeakHint: 'Render the interface in grayscale', documentTitle: 'Page title', documentTitleHint: 'Show the current page title in the browser tab', width220: 'Narrow (220px)', width244: 'Default (244px)', width280: 'Wide (280px)' },
    notification: { title: 'Notifications', empty: 'No notifications', viewAll: 'View all', time: 'just now' },
    common: { healthy: 'Healthy', review: 'In review', ready: 'Ready', building: 'Building', failed: 'Failed', close: 'Close', back: 'Back', retry: 'Retry', loading: 'Loading', refresh: 'Refresh' },
    feedback: { toast: 'Toast', success: 'Success', info: 'Info', warning: 'Warning', error: 'Error', loading: 'Loading', skeleton: 'Skeleton', toggle: 'Toggle', loaded: 'The content is ready without changing the surrounding layout.' },
    home: { eyebrow: 'OpenSCP workspace', title: 'Resource map', description: 'Keep package indexes, asset components, and developer notes traceable in one place.', openDocs: 'Open docs', openPackage: 'Open package', mockNotice: 'Browser Mock data is active; the Tauri app will read real packages.', packages: 'Packages', resources: 'Resources', assets: 'Assets', failedOperations: 'Failed tasks', recentPackages: 'Recently opened', recentPackagesDescription: 'Continue where you left off in a package.', opens: 'opens', noPackages: 'No packages have been opened yet.', activity: 'Recent activity', noActivity: 'No activity yet', metrics: 'Workspace overview', projects: 'Active projects', deployments: 'Deployments this week', teamMembers: 'Team members', sinceLastWeek: 'from last week', recentActivity: 'Recent activity', activityDescription: 'The latest changes across your workspace', viewAll: 'View all', deploymentCompleted: 'Production deployment completed', projectCreated: 'Created a new project', memberJoined: 'A new teammate joined', production: 'Production', platformStatus: 'Platform status', statusDescription: 'Core services are running normally', healthy: 'Healthy', edgeNetwork: 'Edge network', buildPipeline: 'Build pipeline', activityStream: 'Activity stream', operational: 'Operational', quickActions: 'Quick actions', quickActionsDescription: 'Common workspace tasks', newProject: 'Create a project', newProjectDescription: 'Start a new service from a template', inviteMember: 'Invite a member', inviteMemberDescription: 'Add a collaborator to your team', reviewDeployments: 'Review deployments', reviewDeploymentsDescription: 'Inspect recent production releases' },
    projects: { eyebrow: 'Project space', title: 'Projects', description: 'See the health of every service your team operates.', newProject: 'New project', active: 'Active projects', activeDescription: 'Services with recent activity and deployments.', items: 'projects' },
    deployments: { eyebrow: 'Release history', title: 'Deployments', description: 'Track recent releases across production and preview environments.', deploy: 'Create deployment', deployment: 'Deployment', environment: 'Environment', status: 'Status', duration: 'Duration', updated: 'Updated' },
    settings: { eyebrow: 'Workspace configuration', title: 'Settings', description: 'Manage team preferences and notification delivery.', workspaceName: 'Workspace name', notifications: 'Deployment notifications', notificationsDescription: 'Notify the team when production deployments complete.', save: 'Save changes', saved: 'Changes saved', gameDirectoryTitle: 'Game data directory', gameDirectoryDescription: 'The local directory used to discover SimCity packages and resources.', gameDirectoryLabel: 'Directory path', gameDirectoryPlaceholder: 'For example: D:/ea-games/SimCity', gameDirectoryUnavailable: 'This directory is unavailable. Choose it again.', detectedCandidates: 'Detected directories', packageMarkerFound: 'Package file found', noPackageMarker: 'No direct package file found', workspaceTitle: 'Documentation workspace', workspaceDescription: 'Organize Markdown documentation by mod, asset, and component.', workspaceNotConfigured: 'No documentation workspace selected', openWorkspace: 'Open workspace' },
    workspace: { eyebrow: 'Developer docs', title: 'Documentation workspace', description: 'Organize mods, assets, and components so every decision has a place.', chooseTitle: 'Choose a documentation workspace', chooseDescription: 'The workspace stores Markdown files; OpenSCP records folder and README relationships as relative paths.', rootLabel: 'Workspace path', rootPlaceholder: 'Enter a local folder path', openRoot: 'Set workspace', newFolder: 'New folder', folderPlaceholder: 'mods/example', createFolder: 'Create with README', folders: 'Folders', empty: 'No folders yet. Create the first mod or asset directory.', revision: 'Revision', preview: 'Preview', edit: 'Edit', save: 'Save Markdown', markdownLabel: 'Markdown content', selectTitle: 'Select a folder', selectDescription: 'Choose a folder on the left to open its README.md.' },
    runtime: { browserNotice: 'You are viewing the browser preview; Tauri file features are available in the desktop app.' },
    package: { eyebrow: 'Resource browser', title: 'Source parsing', ideDescription: 'Browse game folders, packages, and resources like an IDE.', fileTree: 'File tree', packageFiles: 'Package files', noFolders: 'No folder selected', noPackagesInFolder: 'No packages in this folder', chooseFolderHint: 'Choose a folder from the import menu above.', importMode: 'Import mode', chooseFolder: 'Choose folder', useDefaultFolder: 'Use default directory', import: 'Import', mockSource: 'Browser Mock data', liveSource: 'Live Tauri data', openPackages: 'Open packages', resourceCategories: 'Resource categories', all: 'All', rw4: 'RW4', raster: 'Raster', property: 'Property', text: 'Text', media: 'Media', tgi: 'TGI', storage: 'Storage', compression: 'Compression', compressed: 'Compressed', stored: 'Stored', noCategoryResources: 'No resources in this category', adjustCategory: 'Choose another category to continue.', emptyWorkspaceTitle: 'Workspace ready', emptyWorkspaceDescription: 'Choose a folder on the left, then open a package.', selectPackageTitle: 'Select a package', selectPackageDescription: 'Packages open here as independent tabs.', emptyDetailTitle: 'Select a resource', emptyDetailDescription: 'Resource details appear in this workspace.', bytesReady: 'Choose Hex, text, or another preview.', hex: 'Hex', preview: 'Preview', runtimeNotice: 'This is a browser preview. Open packages from the Tauri desktop app.', pathLabel: 'Package path', pathPlaceholder: 'D:/ea-games/SimCity/SimCityData/…', open: 'Open package', resources: 'resources', resourceList: 'Resource list', pageSummary: 'Page {page} · {total} items', filterPlaceholder: 'Filter by TGI', emptyTitle: 'No resources', emptyDescription: 'This package has no indexed resources to display.', resourceDetail: 'Resource detail', offset: 'File offset', storedSize: 'Stored size', decompressedSize: 'Decompressed size', hexPreview: 'First 4KB', noBytes: 'No bytes read', selectResource: 'Select a resource to inspect it' },
    showcase: { eyebrow: 'Design system showcase', componentsTitle: 'Components', componentsDescription: 'Core interaction states and surface hierarchy for console interfaces.', chartsTitle: 'ECharts', chartsDescription: 'A responsive chart example with on-demand registration.', traffic: 'Platform traffic', trafficDescription: 'Request and deployment trends.', lastSevenDays: 'Last 7 days', iconsTitle: 'Icons', iconsDescription: 'FIcon ships a common Lucide icon set with name, route-alias, color, and size support; extra icons are registered by the app.', registeredIconsTitle: 'App-registered icons', registeredIconsDescription: 'Icons outside the built-in set are registered explicitly by the app via registerIcons before use.', tableTitle: 'Data table', tableDescription: 'Local and requested data, pagination, and loading states.', filter: 'Filter projects…', noResults: 'No matching records', formsTitle: 'Forms', formsDescription: 'Compose fields manually or render them from columns.', manualForm: 'Manual form', autoForm: 'Auto form', feedbackTitle: 'Feedback', feedbackDescription: 'Toast, skeleton, spinner, and empty states reduce perceived wait time.', resultsTitle: 'Results', resultsDescription: 'Standard next steps after success, warning, or failure.', tokensTitle: 'Design tokens', tokensDescription: 'Semantic colors, radii, and shadows used by the app shell.' },
    components: { buttons: 'Buttons', code: 'Code block', markdown: 'Markdown preview', inputs: 'Inputs', formField: 'Form field', loading: 'Loading', results: 'Results', toast: 'Toast', primary: 'Primary', secondary: 'Secondary', ghost: 'Ghost', danger: 'Danger', loadingDemo: 'Loading', disabled: 'Disabled', text: 'Text input', email: 'Email', password: 'Password', select: 'Select', textarea: 'Textarea', checkbox: 'Checkbox', optionA: 'Option A', optionB: 'Option B', optionC: 'Option C', textPlaceholder: 'Type something…', textareaPlaceholder: 'Write a description…', requiredLabel: 'Required field', helpLabel: 'Field with help', errorLabel: 'Field with error', requiredHint: 'Marked as required', helpHint: 'A short help message.', errorHint: 'This field is invalid', spinnerSm: 'Small', spinnerMd: 'Default', resultSuccess: 'Deployment ready', resultSuccessDesc: 'Production has received the latest build.', resultInfo: 'New notification', resultInfoDesc: 'There is a new message from your team.', resultWarning: 'Confirm release', resultWarningDesc: 'Review release settings before continuing.', resultError: 'Request failed', resultErrorDesc: 'The service is temporarily unavailable. Try again later.', toastSuccess: 'Success', toastInfo: 'Info', toastWarning: 'Warning', toastError: 'Error', empty: 'Empty state', emptyTitle: 'No projects yet', emptyDesc: 'Your first project will appear here.', emptyAction: 'Create project', emptyFilteredTitle: 'No matching results', emptyFilteredDesc: 'Adjust the filters and try again.', upload: 'File upload', uploadProgress: 'Upload progress' },
    table: { name: 'Name', owner: 'Owner', status: 'Status', updated: 'Updated', page: 'Page {page}', total: '{total} total', previous: 'Previous', next: 'Next', refresh: 'Refresh data', remote: 'Request data', loadError: 'Failed to load data, please try again' },
    form: { submit: 'Submit', reset: 'Reset', required: 'This field is required', pattern: 'The value has an invalid format', name: 'Name', email: 'Email address', role: 'Role', bio: 'Bio', subscribe: 'Receive updates', namePlaceholder: 'Enter a display name', emailPlaceholder: "name{'@'}example.com", bioPlaceholder: 'Tell us about your work', saved: 'Form submitted' },
    code: { copy: 'Copy', copied: 'Copied', collapse: 'Collapse code', expand: 'Expand code' },
    toast: { dismiss: 'Dismiss notification', success: 'Action completed', info: 'Demo content updated', warning: 'Review the form first', error: 'The request could not complete' },
    login: { eyebrow: 'Fluffy Console', slogan: 'Make every delivery clearer.', description: 'Manage projects, releases, and team activity in one calm workspace.', welcome: 'Welcome back', detail: 'Enter a demo account to access the console.', email: 'Email address', password: 'Password', passwordPlaceholder: 'Enter any password', submit: 'Enter console', success: 'Login demo completed' },
    result: { successTitle: 'Deployment is ready', successDescription: 'Production has received the latest build.', warningTitle: 'One confirmation remains', warningDescription: 'Review release settings before continuing.', errorTitle: 'The request could not complete', errorDescription: 'No data changed. Adjust it and try again.', infoTitle: 'No results yet', infoDescription: 'Your first record will appear here.', viewProjects: 'View projects' },
    tokens: { colors: 'Semantic colors', surfaces: 'Surface layers', radius: 'Radii', shadows: 'Shadows', focus: 'Focus ring' },
    external: { eyebrow: 'External resource', description: 'This page renders in a restricted iframe. Open it in a new tab if the site blocks embedding.', openNewTab: 'Open in new tab', unavailable: 'This external resource is unavailable' },
    notFound: { eyebrow: '404', title: 'This page does not exist', description: 'The link may be outdated or the resource has moved.', path: 'Missing path', action: 'Back to overview', back: 'Go back' },
    upload: { center: { title: 'Upload center', clearCompleted: 'Clear completed', empty: 'No upload tasks', manage: 'Manage uploads' }, tab: { uploading: 'Uploading', done: 'Completed', failed: 'Failed' }, status: { uploading: 'Uploading', done: 'Completed', error: 'Failed' }, dropzone: 'Click or drag files here to upload', simulated: 'OSS is not configured, upload is simulated', retry: 'Retry', remove: 'Remove', error: { failed: 'Upload failed, please retry' } }
  }
}

export const i18n = createI18n({ legacy: false, locale: appConfig.defaultLocale, fallbackLocale: 'en-US', messages })
