<script setup lang="ts">
import { computed, onBeforeUnmount, shallowRef } from 'vue'
import type { AppTab } from '@/stores/tabs'

interface Props { tabs: AppTab[]; activePath: string }
interface Emits { activate: [path: string]; reload: [path: string]; closeCurrent: [path: string]; closeLeft: [path: string]; closeRight: [path: string]; closeOthers: [path: string]; closeAll: [] }
const props = defineProps<Props>()
const emit = defineEmits<Emits>()
const contextPath = shallowRef('')
const contextPosition = shallowRef({ x: 0, y: 0 })
const contextIndex = computed(() => props.tabs.findIndex((tab) => tab.fullPath === contextPath.value))
const hasClosableLeft = computed(() => props.tabs.slice(0, contextIndex.value).some((tab) => tab.closable))
const hasClosableRight = computed(() => props.tabs.slice(contextIndex.value + 1).some((tab) => tab.closable))
const hasClosableOthers = computed(() => props.tabs.some((tab) => tab.closable && tab.fullPath !== contextPath.value))
const hasClosableTabs = computed(() => props.tabs.some((tab) => tab.closable))

function openContextMenu(event: MouseEvent, path: string) {
  event.preventDefault()
  contextPath.value = path
  contextPosition.value = { x: Math.min(event.clientX, window.innerWidth - 196), y: Math.min(event.clientY, window.innerHeight - 250) }
}
function closeContextMenu() { contextPath.value = '' }
function run(action: () => void) { action(); closeContextMenu() }
function onKeydown(event: KeyboardEvent) { if (event.key === 'Escape') closeContextMenu() }
window.addEventListener('keydown', onKeydown)
onBeforeUnmount(() => window.removeEventListener('keydown', onKeydown))
</script>
<template><section v-if="props.tabs.length" class="tab-bar" :aria-label="$t('shell.tabs')"><div class="tab-scroll" role="tablist"><button v-for="tab in props.tabs" :key="tab.fullPath" class="tab" :class="{ active:tab.fullPath===props.activePath }" type="button" role="tab" :aria-selected="tab.fullPath===props.activePath" @click="emit('activate',tab.fullPath)" @contextmenu="openContextMenu($event,tab.fullPath)"><span class="tab-title">{{ $t(tab.titleKey) }}</span><span v-if="tab.closable" class="tab-close" :aria-label="$t('shell.closeTab')" @click.stop="emit('closeCurrent',tab.fullPath)"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m7 7 10 10M17 7 7 17" /></svg></span></button></div><div class="tab-actions"><button class="tab-action" type="button" :aria-label="$t('shell.closeOthers')" :disabled="!hasClosableOthers" @click="emit('closeOthers',props.activePath)"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 7h14M8 12h8M10 17h4"/></svg></button><button class="tab-action" type="button" :aria-label="$t('shell.closeAll')" :disabled="!hasClosableTabs" @click="emit('closeAll')"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 7h12M9 7V5h6v2M10 11v6M14 11v6M7 7l1 13h8l1-13"/></svg></button></div></section><Teleport to="body"><div v-if="contextPath" class="context-overlay" @mousedown="closeContextMenu"><div class="context-menu" :style="{ left:`${contextPosition.x}px`, top:`${contextPosition.y}px` }" role="menu" @mousedown.stop><button type="button" role="menuitem" @click="run(()=>emit('reload',contextPath))">{{ $t('shell.reload') }}</button><div class="separator"/><button type="button" role="menuitem" :disabled="!props.tabs[contextIndex]?.closable" @click="run(()=>emit('closeCurrent',contextPath))">{{ $t('shell.closeCurrent') }}</button><button type="button" role="menuitem" :disabled="!hasClosableLeft" @click="run(()=>emit('closeLeft',contextPath))">{{ $t('shell.closeLeft') }}</button><button type="button" role="menuitem" :disabled="!hasClosableRight" @click="run(()=>emit('closeRight',contextPath))">{{ $t('shell.closeRight') }}</button><div class="separator"/><button type="button" role="menuitem" :disabled="!hasClosableOthers" @click="run(()=>emit('closeOthers',contextPath))">{{ $t('shell.closeOthers') }}</button><button type="button" role="menuitem" :disabled="!hasClosableTabs" @click="run(()=>emit('closeAll'))">{{ $t('shell.closeAll') }}</button></div></div></Teleport></template>
<style scoped>
.tab-bar{align-items:stretch;background:var(--surface);border-bottom:1px solid var(--border);display:flex;min-width:0}.tab-scroll{display:flex;flex:1;gap:2px;min-width:0;overflow-x:auto;scrollbar-width:thin}.tab{align-items:center;background:transparent;border:0;border-bottom:2px solid transparent;color:var(--muted-foreground);cursor:pointer;display:inline-flex;flex:none;font-size:12px;gap:8px;max-width:220px;min-height:42px;padding:0 12px;transition:background-color 140ms ease,border-color 140ms ease,color 140ms ease,scale 140ms ease}.tab:hover{background:var(--surface-hover);color:var(--foreground)}.tab:active{scale:.98}.tab.active{border-bottom-color:var(--primary);color:var(--foreground);font-weight:650}.tab-title{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.tab-close{align-items:center;border-radius:4px;display:inline-flex;height:20px;justify-content:center;width:20px}.tab-close:hover{background:var(--border);color:var(--danger)}.tab-close svg,.tab-action svg{fill:none;height:14px;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:1.8;width:14px}.tab-actions{align-items:center;border-left:1px solid var(--border);display:flex;gap:2px;padding:0 8px}.tab-action{align-items:center;background:transparent;border:0;border-radius:var(--radius-sm);color:var(--muted-foreground);cursor:pointer;display:inline-flex;height:30px;justify-content:center;width:30px;transition:background-color 140ms ease,color 140ms ease,scale 140ms ease}.tab-action:hover:not(:disabled){background:var(--surface-hover);color:var(--foreground)}.tab-action:active:not(:disabled){scale:.96}.tab-action:disabled{cursor:not-allowed;opacity:.4}.context-overlay{inset:0;position:fixed;z-index:90}.context-menu{background:var(--surface-elevated);border:1px solid var(--border);border-radius:var(--radius-md);box-shadow:var(--shadow-md);padding:5px;position:fixed;width:190px}.context-menu button{background:transparent;border:0;border-radius:var(--radius-sm);color:var(--foreground);cursor:pointer;font-size:12px;padding:8px 9px;text-align:start;width:100%}.context-menu button:hover:not(:disabled){background:var(--surface-hover)}.context-menu button:disabled{color:var(--subtle-foreground);cursor:not-allowed}.separator{background:var(--border);height:1px;margin:5px}@media(max-width:600px){.tab{max-width:160px;padding-inline:10px}.tab-actions{padding-inline:4px}.tab-action{width:28px}}
</style>
