<script setup lang="ts">
import FIcon from '@/components/extensions/FIcon.vue'
import { builtinIconNames } from '@/lib/icons'
const registeredIcons = ['calendar-days']
const registerSample = `import { CalendarDays } from 'lucide-vue-next'
import { registerIcons } from '@/lib/icons'

registerIcons({ CalendarDays })`
</script>
<template><section class="page"><header><p class="eyebrow">{{ $t('showcase.eyebrow') }}</p><h1>{{ $t('showcase.iconsTitle') }}</h1><p>{{ $t('showcase.iconsDescription') }}</p></header><div class="icon-grid"><article v-for="icon in builtinIconNames" :key="icon" class="icon-card"><FIcon :name="icon" color="var(--primary)" :size="22" /><span>{{ icon }}</span></article></div><article class="panel"><h2>{{ $t('showcase.registeredIconsTitle') }}</h2><p>{{ $t('showcase.registeredIconsDescription') }}</p><div class="icon-grid registered"><article v-for="icon in registeredIcons" :key="icon" class="icon-card"><FIcon :name="icon" color="var(--primary)" :size="22" /><span>{{ icon }}</span></article></div><pre class="code-hint">{{ registerSample }}</pre></article></section></template>
<style scoped>.page{display:grid;gap:24px}.eyebrow{color:var(--primary);font-size:11px;font-weight:750;letter-spacing:.08em;margin:0 0 10px;text-transform:uppercase}h1{font-size:clamp(1.8rem,3vw,2.5rem);letter-spacing:-.045em;margin:0}header p:not(.eyebrow){color:var(--muted-foreground);font-size:14px;margin:10px 0 0}.icon-grid{display:grid;gap:10px;grid-template-columns:repeat(auto-fill,minmax(88px,1fr))}.icon-card{align-items:center;background:var(--surface);border:1px solid var(--border);border-radius:var(--radius-lg);color:var(--muted-foreground);display:grid;gap:10px;justify-items:center;padding:14px}.icon-card span{font-family:ui-monospace,monospace;font-size:11px;max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.panel{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius-lg);box-shadow:var(--shadow-sm);display:grid;gap:14px;padding:20px}.panel h2{font-size:14px;margin:0}.panel p{color:var(--muted-foreground);font-size:13px;margin:0}.registered{max-width:440px}.code-hint{background:var(--surface-hover);border:1px solid var(--border);border-radius:var(--radius-sm);color:var(--muted-foreground);font-family:ui-monospace,monospace;font-size:12px;line-height:1.6;margin:0;overflow:auto;padding:12px}@media(max-width:600px){.icon-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}</style>